---
development:
  cloud_name: dtuelimex
  api_key: '142461677577871'
  api_secret: Gqf5zsM813YqJVjlHVVpuYDBKN0
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dtuelimex
  api_key: '142461677577871'
  api_secret: Gqf5zsM813YqJVjlHVVpuYDBKN0
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dtuelimex
  api_key: '142461677577871'
  api_secret: Gqf5zsM813YqJVjlHVVpuYDBKN0
  enhance_image_tag: true
  static_image_support: false
