# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9058fb489d8e5625601d6636154c66dde1fa90a7309c225be395efa4be3138c48f725db5589777226aece5e5879fb83683b331fee0e6985383b931275dbbff7b

test:
  secret_key_base: 74023a946daed41c9b2306297073bd4e85b38f1ba6638bf21beb7a9809b213cd395d69fc850bc40ccf1a05965f2d6094737582b8d4948e7ee11130a86de9aa12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
